Fix handling missing pasted text.
Fixes:

    Traceback (most recent call last):
      File ".../yt-dlg/./yt-dlg", line 84, in on_accel
        urls = get_urls(text)
               ^^^^^^^^^^^^^^
      File ".../yt-dlg/./yt-dlg", line 56, in get_urls
        return re.findall(r'^https?://\S+', text, flags=re.M)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/re/__init__.py", line 216, in findall
        return _compile(pattern, flags).findall(string)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: expected string or bytes-like object, got 'NoneType'